version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8800:8800"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}

  frontend:
    build: ./frontend
    ports:
      - "80:5173"