version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    # Only expose port 8800 internally (no public port mapping)
    expose:
      - "8800"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    # The backend is accessible via "backend:8800" inside Docker

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    # This will serve everything on host port 80
    ports:
      - "80:80"
      - "443:443"  # We’ll listen on 443 inside the container
    depends_on:
      - backend
    volumes:
      - /home/ec2-user/certbot-webroot:/usr/share/nginx/html/.well-known/acme-challenge